### ISSUE TITLE
Error when building: execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by Unzor** [raxod502/python-in-a-box#4]
I am trying to get Python In A Box to work on my computer, but I keep on getting this error:
```
execvp(3) failed.: No such file or directory
```

**Comment by raxod502** [comment]
This might be a dumb question, but... do you have Python installed?

**Comment by Unzor** [comment]
Ah no. I'm actually running it on Replit, and I also have it on my computer, and neither of them worked. I might as well install it to see if it works on my computer

**Comment by raxod502** [comment]
You need to have `python3` on your PATH for the app to be able to run Python.

**Comment by Unzor** [comment]
Ah okay, thanks.
